// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnsureBackend() {
  return window['go']['main']['App']['EnsureBackend']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function OpenLogsDir() {
  return window['go']['main']['App']['OpenLogsDir']();
}

export function ProbeHealth() {
  return window['go']['main']['App']['ProbeHealth']();
}

export function ShutdownBackend() {
  return window['go']['main']['App']['ShutdownBackend']();
}
