// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {fanfan} from '../models';
import {service} from '../models';
import {main} from '../models';

export function DetectFanfan(arg1:string,arg2:string):Promise<fanfan.DetectResult>;

export function EnsureBackend():Promise<service.BootstrapStatus>;

export function ExportLogs(arg1:string):Promise<string>;

export function GetAppInfo():Promise<main.AppInfo>;

export function HideToTray():Promise<void>;

export function LaunchFanfan(arg1:string,arg2:string):Promise<fanfan.DetectResult>;

export function OpenLogsDir():Promise<void>;

export function PickFanfanDirectory():Promise<string>;

export function ProbeHealth():Promise<service.BootstrapStatus>;

export function QuitApp():Promise<void>;

export function RestartApp():Promise<void>;

export function RunDiagnostics():Promise<Array<main.DiagnosticItem>>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function ShowMainWindow():Promise<void>;

export function ShutdownBackend():Promise<void>;
