// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {main} from '../models';

export function EnsureBackend():Promise<service.BootstrapStatus>;

export function GetAppInfo():Promise<main.AppInfo>;

export function OpenLogsDir():Promise<void>;

export function ProbeHealth():Promise<service.BootstrapStatus>;

export function ShutdownBackend():Promise<void>;
